# DATABASE
DROP DATABASE IF EXISTS AUTO_ESCOLA;

CREATE DATABASE AUTO_ESCOLA;

USE AUTO_ESCOLA;


# TABLES
CREATE TABLE IF NOT EXISTS PESSOA (
	HANDLE         INT AUTO_INCREMENT,
	CPF            VARCHAR(11) NOT NULL UNIQUE,
	NOME           VARCHAR(200),
	DATANASCIMENTO DATE NOT NULL,
	TELEFONE       VARCHAR(20),
	EMAIL          VARCHAR(200),
	USUARIO        VARCHAR(100) NOT NULL UNIQUE,
	SENHA          VARCHAR(500),
	QUANTPARCELAS  INT DEFAULT(10),
	VALORPARCELA   INT DEFAULT(200),
	TIPOPESSOA     INT,
	NOTAPRATICA DECIMAL(2,2),
	NOTATEORICA DECIMAL(2,2),
	
	PRIMARY KEY    (HANDLE)
);

CREATE TABLE IF NOT EXISTS PARCELAS (
	HANDLE INT AUTO_INCREMENT,
	NUMEROPARCELA INT,
	DATAPARCELA DATE,
	PESSOA INT,
	PAGO TINYINT(1),
	
	PRIMARY KEY(HANDLE),
	FOREIGN KEY (PESSOA) REFERENCES PESSOA(HANDLE)
);

CREATE TABLE IF NOT EXISTS TURMA(
	HANDLE INT AUTO_INCREMENT,
	CATEGORIA VARCHAR(10),
	DATAINICIO DATE,
	HORARIOAULAS TIME,
	INSTRUTOR INT,
	
	PRIMARY KEY (HANDLE),
	FOREIGN KEY (INSTRUTOR) REFERENCES PESSOA(HANDLE)
);


CREATE TABLE IF NOT EXISTS TURMAALUNO (
	HANDLE      INT AUTO_INCREMENT,
	TURMA       INT,
	PESSOA      INT,
	
	PRIMARY KEY(HANDLE),
	FOREIGN KEY (TURMA) REFERENCES TURMA(HANDLE),
	FOREIGN KEY (PESSOA) REFERENCES PESSOA(HANDLE)
);

CREATE TABLE IF NOT EXISTS DIALETIVO(
	HANDLE INT AUTO_INCREMENT,
	DATAAULA DATE,
	TURMA INT,
	
	PRIMARY KEY (HANDLE),
	FOREIGN KEY (TURMA) REFERENCES TURMA(HANDLE)
);

